### ISSUE TITLE
Not compatible with SoftwareSerial

### ISSUE THREAD

**Issue by haimiko** [lucullusTheOnly/TinyWire#16]
On ATTINY85 this will not compile with SoftwareSerial enabled.  If I remove TinyWire and use "TinyWireS" instead Software serial compiles and works.  This is the compilation error I'm getting:

``` 
SoftwareSerial.cpp.o (symbol from plugin)*: In function SoftwareSerial::read()
(.text+0x0)*: multiple definition of __vector_2
twi.cpp.o (symbol from plugin)*: (.text+0x0): first defined here

Error linking for board ATtiny25/45/85 w/ ATtiny85
 
   In function global constructors keyed to 65535_0_OneI2CSensors_Tiny.cpp.o
 
lto1.exe*: internal compiler error: Segmentation fault
   Please submit a full bug report
   with preprocessed source if appropriate
   gcc.gnu.org\bugs.html> for instructions
 ```

Any idea why?

**Comment by lucullusTheOnly** [comment]
As I remember, the SoftwareSerial library also uses the Pin Change Interrupt, as used in this library to detect the Stop condition (which signals a free bus). You cannot define more than one ISR for the same Interrupt vector and that's what you do with using both libraries. TinyWireS doesn't use this interrupt, since it is only a I2C slave library. It does not have to monitor the bus to check if it is free. It will only do something, when the master requests it to. If you only need slave functionality, but also SoftwareSerial, you should stick to the TinyWireS library.

I will close this issue, since it is resolved (at least from my perspective). If there is anything further related to this issue, please be free to post again and I will reopen it.
