### ISSUE TITLE
USB-I2C gateway

### ISSUE THREAD

**Issue by PizzaProgram** [lucullusTheOnly/TinyWire#23]
**Hi,**
 Sorry for this question, but I'm looking for a way to turn multiple Digispark AtTiny85 boards into unique USB>I2C adapters.

Can this library used somehow to:
 1. simply **load** the program into an Arduino IDE 
 2. **change the name** + Serial (to make those boards unique)
 3. **upload** to the board and use?

(First I have tried [I2C-Tiny-USB](https://github.com/harbaum/I2C-Tiny-USB/tree/master/digispark) but it has [a serious bug = Stops working after reboot](https://github.com/harbaum/I2C-Tiny-USB/issues/13))

Thank you in forward for any solutions!

**Comment by lucullusTheOnly** [comment]
The I2C part of that project wouldn't be the big concern I think. While I'm currently not developing the library and will not guarantee for its work, it should be fine for doing the I2C part. Otherwise you could go to the TinyWireM library. But the bigger part is to build the USB interface. The readme of the linked project states, that the USB interface is done purely in software. You would need to also do that. I think there are already implementations (like V-USB), though I don't know, if these would fit on the ATtiny85.

So the answer would be: It can do the I2C part. The rest is out of scope for me and this repo.

I wish you good luck with your project.
