### ISSUE TITLE
Multi-byte slave writes fail when master does not read all bytes

### ISSUE THREAD

**Issue by felias-fogg** [lucullusTheOnly/TinyWire#9]
If you write multiple bytes in the onRequest function and the master does not consume all the bytes, the remaining bytes will be read next time, which is definitely wrong (the Wire library will delete the remaining bytes). If you do it multiple times, the tx buffer fills up until the program locks.
The fix is to insert the line
`txHead = txTail = 0; `
after line 736.

**Comment by lucullusTheOnly** [comment]
You're right. That would block the library. I will change this.

Also I think of changing the slave_send function itself, so that it cannot block the program flow. The Wire library returns the number of bytes, that were actually send. With my changes the slave_send will not block, but return 0 if the buffer is full. If the byte was correctly written to buffer, it will return 1. In future versions of the library there may be support for other data types, that contain more than 1 byte.
